;; DGO definition file for Open Mines level
;; We use the convention of having a longer DGO name for levels without precomputed visibility.

;; the actual file name still needs to be 8.3
("OPM.DGO"
 ("static-screen.o"
  "plat-ag.go"
  "mis-bone-bridge-ag.go"
  "mis-bone-platform-ag.go"
  "water-anim-maincave-ag.go"
  "water-anim-maincave-water-ag.go"
  "citb-button-ag.go"
  "plat-ag.go"
  "plat-eco-ag.go"
  "citb-drop-plat-ag.go"
  "keg-ag.go"
  "keg-conveyor-ag.go"
  "keg-conveyor-paddle-ag.go"
  "citb-firehose-ag.go"
  "generic-button-ag.go"
  "cavecrusher-ag.go"
  "caveelevator-ag.go"
  "mayorgears-ag.go"
  "babak-ag.go"
  "bonelurker-ag.go"
  "mistycam-ag.go"
  "green-eco-lurker-ag.go"
  "misty-conveyor.o"
  "mines-part.o"
  "battlecontroller.o"
  "mines-obs.o"
  "bonelurker.o"
  "green-eco-lurker.o"
  "open-mines.go" 
 ))