name: 🏭 Cut Mod Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Semver Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  cut_release:
    name: "Cut Release"
    uses: open-goal/mod-bundling-tools/.github/workflows/mod-bundler.yml@v1
    with:
      semverBump: ${{ inputs.bump }}
      metadataName: "TFL"
      metadataDescription: "Jak and Daxter: The Forgotten Lands - Chapter 2"
      metadataSupportedGames: "jak1"
      metadataAuthors: "kuitar"
      metadataTags: "beta,custom-level,texture-mod"
      metadataWebsiteUrl: "https://github.com/Kuitar5/the-forgotten-lands"
      skipMacOS: true
      toolingBinaryDir: "out/build/Release/bin"
      gameAssetsDir: "./game/assets"
      copyEntireBinaryDir: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
